server:
  port: 2233
#############################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///imooc_foodie_shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      max-lifetime: 1800000
      # 连接时测试
      connection-test-query: SELECT 1
#############################################
mybatis-plus:
  type-aliases-package: com.liuxi.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml